---
- name: Populate hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_eth0']['ipv4']['address'] }}   {{ item }}"
  with_items: "{{ ansible_play_batch }}"

- name: Set local nameserver
  lineinfile:
    path: /etc/resolv.conf
    regexp: "^nameserver "
    line: "nameserver {{ local_dns_server }}"

