---
- name: Create directories
  file:
    path: /root/.config/openshift/
    state: directory
    
- name: Create openshift/installer.cfg.yml
  template:
    src: config_openshift_installer.cfg.yml.j2
    dest: /root/.config/openshift/installer.cfg.yml

- name: Create openshift/hosts
  template:
    src: config_openshift_hosts.j2
    dest: /root/.config/openshift/hosts

# TODO - elegant way to launch and control ansible-based installer playbooks?

